In [3]:
#Importing libraries
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import joblib

In [4]:
#Reading the dataset
df = pd.read_csv('Linear_regression_dataset.csv',header='infer')
df.sample(3)

var_1  var_2  var_3  var_4  var_5  output
483     898    794     85  0.360  0.281   0.447
406     686    845     63  0.328  0.264   0.384
1096    612    611     84  0.298  0.242   0.366

In [5]:
X = df.loc[:,df.columns !='output']
X

var_1  var_2  var_3  var_4  var_5
0       734    688     81  0.328  0.259
1       700    600     94  0.320  0.247
2       712    705     93  0.311  0.247
3       734    806     69  0.315  0.260
4       613    759     61  0.302  0.240
...     ...    ...    ...    ...    ...
1227    705    759     81  0.330  0.260
1228    706    626     93  0.321  0.268
1229    878    690    103  0.341  0.278
1230    774    664     84  0.335  0.271
1231    599    716     60  0.308  0.250

[1232 rows x 5 columns]

In [6]:
y = df['output']

In [7]:
lr = LinearRegression().fit(X,y)

In [8]:
lr.score(X,y)

0.8692670151914198

In [13]:
import numpy as np
pred_args=[5.0,7.0,8.0,10.0,11.0]
print(pred_args)
pred_arr=np.array(pred_args)
print(pred_arr)
preds=pred_arr.reshape(1,-1)
print(preds)

model_prediction = lr.predict(preds)
print(model_prediction)
mdel_prediction = round(float(model_prediction),2)
mdel_prediction

[5.0, 7.0, 8.0, 10.0, 11.0]
[ 5.  7.  8. 10. 11.]
[[ 5.  7.  8. 10. 11.]]
[-0.91182997]


-0.91

In [9]:
#We make use of the joblib library that serializes the
#model (saves coefficient values for input variables as a dictionary).

joblib.dump(lr,'linear_regression_model.pkl')

['linear_regression_model.pkl']

In [10]:
import numpy as np
pred_args=[5.0,7.0,8.0,10.0,11.0]
print(pred_args)
pred_arr=np.array(pred_args)
print(pred_arr)
preds=pred_arr.reshape(1,-1)
print(preds)

[5.0, 7.0, 8.0, 10.0, 11.0]
[ 5.  7.  8. 10. 11.]
[[ 5.  7.  8. 10. 11.]]
